-- 식품 정보 FOOD_PRODUCT
-- PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
-- 식품 ID, 식품 이름, 식품코드, 식품분류, 식품 가격

-- 테이블과 식품의 주문 정보 FOOD_ORDER
-- ORDER_ID, PRODUCT_ID, AMOUNT, PRODUCE_DATE, IN_DATE, OUT_DATE, FACTORY_ID, WAREHOUSE_ID
-- 주문 ID, 제품 ID, 주문량, 생산일자, 입고일자, 출고일자, 공장 ID, 창고 ID

-- 생산일자가 2022-05인 식품의 총매출
-- 정렬: 총매출 내림차순, 식품 ID 오름차순

SELECT F.PRODUCT_ID, F.PRODUCT_NAME, (P.TOTAL_AMOUNT * F.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS F
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID
) AS P ON F.PRODUCT_ID = P.PRODUCT_ID 
ORDER BY TOTAL_SALES DESC, F.PRODUCT_ID 