-- 고객 정보 MEMBER_PROFILE
-- MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH
-- 회원 ID, 회원 이름, 회원 연락처, 성별, 생년월일
-- 테이블과 식당 리뷰 정보 REST_REVIEW
-- REVIEW_ID, REST_ID, MEMBER_ID, REVIEW_SCORE, REVIEW_TEXT,REVIEW_DAT
-- 리뷰 ID, 식당 ID, 회원 ID, 점수, 리뷰 텍스트, 리뷰 작성일

-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
-- 정렬: 리뷰 작성일 오름차순, 텍스트 오름차순

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS M
JOIN REST_REVIEW AS R ON M.MEMBER_ID = R.MEMBER_ID
JOIN (
    SELECT R2.MEMBER_ID, COUNT(*) AS CNT
    FROM REST_REVIEW AS R2
    GROUP BY R2.MEMBER_ID
    ORDER BY CNT DESC
    limit 1
) AS R3
WHERE M.MEMBER_ID = R3.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT

